### ISSUE TITLE
variables in the RDR Help document not filled with value

### ISSUE THREAD

**Issue by hurngchunlee** [Radboud-University/rdr-configurable-content#94] opened 2020-12-04 09:05 UTC
@paulspeijers @robertoostenveld  I noticed that on the RDR help page, variables are not properly replaced with right value.

e.g. https://data.ru.nl/doc/help/user-manual/transfer-data/cadaver.html

comparing with https://data.donders.ru.nl/doc/help/user-manual/transfer-data/cadaver.html.

Also the command table at the end of the page is not shown on RDR website.

**Comment by hurngchunlee** [comment] 2020-12-04 09:20
When build locally, I noticed the following Sphinx warnings:

```
/tmp/tmp.gYo2UFoWKX/index.rst:9: WARNING: Title underline too short.

${repositoryDescription}
==================
/tmp/tmp.gYo2UFoWKX/rdm-nutshell.rst:4: WARNING: Title underline too short.

The ${repositoryDescription} in a nutshell
====================================
/tmp/tmp.gYo2UFoWKX/user-manual/transfer-data/cadaver.rst:115: WARNING: Malformed table.
```

So the issue here is the length of the underline bar `====` should match the length of the title.  When the variable is replaced with right value, before or after the build?

**Comment by paulspeijers** [comment] 2020-12-04 14:19
The problem is that during the build from .rst to .html the following transformation is performed:

before conversion:
```
Open the Linux terminal and type the following command.

.. code-block:: bash

    $ cadaver ${repositoryWebdavUrl}
```

after conversion:
```
<p>Open the Linux terminal and type the following command.</p>
<div class="highlight-bash notranslate"><div class="highlight"><pre><span></span>$ cadaver <span class="si">${</span><span class="nv">repositoryWebdavUrl</span><span class="si">}</span>
</pre></div>
</div>
```

Because of all this processing our template engine (FreeMarker) does not see this as a variable anymore, so it's not replaced. Any ideas?

**Comment by paulspeijers** [comment] 2020-12-04 14:20
By the way the reason that it does work on DR prod is that the usage of variables has not been merged to the dr-release branch for the configurable content.

**Comment by hurngchunlee** [comment] 2020-12-04 16:31
> The problem is that during the build from .rst to .html the following transformation is performed:
> 
> before conversion:
> 
> ```
> Open the Linux terminal and type the following command.
> 
> .. code-block:: bash
> 
>     $ cadaver ${repositoryWebdavUrl}
> ```
> 
> after conversion:
> 
> ```
> <p>Open the Linux terminal and type the following command.</p>
> <div class="highlight-bash notranslate"><div class="highlight"><pre><span></span>$ cadaver <span class="si">${</span><span class="nv">repositoryWebdavUrl</span><span class="si">}</span>
> </pre></div>
> </div>
> ```
> 
> Because of all this processing our template engine (FreeMarker) does not see this as a variable anymore, so it's not replaced. Any ideas?

I managed to disable the code-block highlighting with 

```
.. code-block: none

    $ cadaver ${repositoryWebdavUrl}
```

and the end result in HTML becomes

```html
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>$ cadaver ${repositoryWebdavUrl}
</pre></div>
</div>
```

see change in https://github.com/Radboud-University/rdr-configurable-content/commit/8e632c7d77f1f60b09224078571b0b8c9a2c98c0

**Comment by paulspeijers** [comment] 2020-12-08 10:24
It works. I have merged this change to all branches.

**Closed by paulspeijers** 2020-12-08 10:24 UTC
